config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"

  namespace :admin do
    resources :posts, only: [:index, :show, :update, :destroy]
    resources :users, only: [:index, :show, :update]
    resources :comments, only: [:index, :show, :destroy]
    resources :boards, only: [:index, :show, :destroy]
    resources :board_comments, only: [:index, :show, :destroy]
    resources :searches, only: :index
    get"search" => "searches#search"
  end

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, controllers: {
    sessions: "public/sessions",
    registrations: "public/registrations"
  }

  scope module: :public do
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :edit, :update, :destroy]
    end
    resources :searches, only: :index
    get"search" => "searches#search"
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get"followings" => "relationships#followings", as: "followings"
      get"followers" => "relationships#followers", as: "followers"
      member do
        get :favorites
      end
    end
    resources :boards, only: [:new, :index, :show, :create] do
      resources :board_comments, only: [:create], shallow: true
    end
    resources :notifications, only: :index
    resources :mini_messages, only: :create
    resources :mini_rooms, only: [:create,:index,:show]
    get "user/confirm" => "users#confirm" #退会確認画面
    patch "user/withdrawal" => "users#withdrawal" #論理削除用のルーティング
    post "guest_sign_in" => "sessions#guest_sign_in" #ゲストログイン用のルーティング
  end

 devise_scope :user do
   post "users/guest_sign_in" => "public/sessions#guest_sign_in"
 end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/board_comment.rb
class BoardComment < ApplicationRecord
  belongs_to :user
  belongs_to :board

  validates :body, presence: true, length: { maximum: 1_500 }
end

app/controllers/admin/board_comments_controller.rb
class Admin::BoardCommentsController < ApplicationController
  def index
    @board_comments = BoardComment.all
  end

  def show
    @board_comment = BoardComment.find(params[:id])
  end

  def destroy
    bc = BoardComment.find(params[:id])
    if bc.destroy
      flash[:notice] = "削除しました。"
      redirect_to admin_board_comments_path
    else
      flash.now[:alert] = "削除に失敗しました。"
      render :show
    end
  end

  private
    def board_comment_params
      params.require(:board_comment).permit(:body)
    end
end

app/helpers/admin/board_comments_helper.rb
module Admin::BoardCommentsHelper
end

app/views/admin/board_comments/index.html.erb
<h1 class="text-center">掲示板コメント一覧</h1>
<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
      <th>ID</th>
      <th>本文</th>
      <th>作成ユーザー</th>
      <th>投稿先掲示板タイトル</th>
      <th>掲示板ID</th>
      </tr>
    </thead>
    <tbody>
      <% @board_comments.each do |bc|%>
      <tr class="moves-contents" onclick='window.location="/admin/board_comments/<%= bc.id %>"' role="link">
        <td><%= bc.id %></td>
        <td><%= bc.body %></td>
        <td><%= image_tag bc.user.get_image(30,30) %><%= bc.user.name %></td>
        <td><%= link_to bc.board.title,admin_board_path(bc.board) %></td>
        <td><%= link_to bc.board_id,admin_board_path(bc.board),class: "text" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/board_comments/show.html.erb
<h1 class="text-center">掲示板コメント情報</h1>
<div class="row-fluid">
  <table class="table col-8 offset-md-2">
    <tr><th>コメントID</th><td><%= @board_comment.id %></td></tr>
    <tr><th>コメントユーザー</th><td><%= link_to admin_users_path(@board_comment.user) do %>
      <%= image_tag @board_comment.user.get_image(30,30) %><%= @board_comment.user.name %>
    <% end %></td></tr>
    <tr class="pb-0 mb-0"><th>コメント本文</th><td><%= @board_comment.body %></td></tr>
  </table>
  <%= link_to "コメントを削除する",admin_board_comment_path(@board_comment),method: :delete,class: "offset-md-6 pt-0 mt-0" %>
</div>
<div class="row-fluid pt-5">
  <table class="table table-hover col-8 offset-md-2">
    <tr class="moves-contents" onclick='window.location="/admin/boards/<%= @board_comment.board_id %>"' role="link">
      <th>コメント先の掲示板</th><td><%= @board_comment.board.title %></td>
    </tr>
    <tr class="moves-contents" onclick='window.location="/admin/boards/<%= @board_comment.board_id %>"' role="link">
      <th>掲示板の本文</th><td><%= @board_comment.board.body %></td>
    <tr class="moves-contents" onclick='window.location="/admin/users/<%= @board_comment.board.user.id %>"' role="link">
      <th>投稿ユーザー</th><td><%= image_tag @board_comment.board.user.get_image(30,30) %><%= @board_comment.board.user.name %></td>
  </table>
</div>