config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"

  namespace :admin do
    resources :posts, only: [:index, :show, :update, :destroy]
    resources :users, only: [:index, :show, :update]
    resources :comments, only: [:index, :show, :destroy]
    resources :boards, only: [:index, :show, :destroy]
    resources :board_comments, only: [:index, :show, :destroy]
    resources :searches, only: :index
    get"search" => "searches#search"
  end

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, controllers: {
    sessions: "public/sessions",
    registrations: "public/registrations"
  }

  scope module: :public do
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :edit, :update, :destroy]
    end
    resources :searches, only: :index
    get"search" => "searches#search"
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get"followings" => "relationships#followings", as: "followings"
      get"followers" => "relationships#followers", as: "followers"
      member do
        get :favorites
      end
    end
    resources :boards, only: [:new, :index, :show, :create] do
      resources :board_comments, only: [:create], shallow: true
    end
    resources :notifications, only: :index
    resources :mini_messages, only: :create
    resources :mini_rooms, only: [:create,:index,:show]
    get "user/confirm" => "users#confirm" #退会確認画面
    patch "user/withdrawal" => "users#withdrawal" #論理削除用のルーティング
    post "guest_sign_in" => "sessions#guest_sign_in" #ゲストログイン用のルーティング
  end

 devise_scope :user do
   post "users/guest_sign_in" => "public/sessions#guest_sign_in"
 end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user

  has_many :board_comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 20 }#「presence: true」で入力必須。「length: { maximum:  }」は文字数制限のバリデーション。今回は、２５５字以内という制限。
  validates :body, presence: true, length: { maximum: 1_500 }
end

app/controllers/admin/boards_controller.rb
class Admin::BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def show
    @board = Board.find(params[:id])
  end

  def destroy
    board = Board.find(params[:id])
    if board.destroy
      flash[:notice] = "削除しました。"
      redirect_to admin_boards_path
    else
      flash[:alert] = "削除に失敗しました。"
      render :show
    end
  end

  private
    def board_params
      params.require(:board).permit(:title, :body)
    end
end

app/helpers/admin/boards_helper.rb
module Admin::BoardsHelper
end

app/views/admin/boards/index.html.erb
<h1 class="text-center">掲示板一覧</h1>
<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
      <th>ID</th>
      <th>掲示板タイトル</th>
      <th>本文</th>
      <th>作成ユーザー</th>
      <th>コメント数</th>
      </tr>
    </thead>
    <tbody>
      <% @boards.each do |b|%>
      <tr class="moves-contents" onclick='window.location="/admin/boards/<%= b.id %>"' role="link">
        <td><%= b.id %></td>
        <td><%= b.title %></td>
        <td><%= b.body %></td>
        <td><%= b.user.name %></td>
        <td><%= b.board_comments.count %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/boards/show.html.erb
<h1 class="text-center">掲示板詳細</h1>
<div class="row-fluid">
  <table class="table col-8 offset-md-2">
    <tr><th>掲示板ID</th><td><%= @board.id %></td></tr>
    <tr><th>掲示板タイトル</th><td><%= @board.title %></td></tr>
    <tr><th>本文</th><td><%= @board.body %></td></tr>
    <tr><th>作成ユーザー</th><td><%= link_to admin_user_path(@board.user) do %>
    <%= image_tag @board.user.get_image(30,30) %><%= @board.user.name %>
    <% end %></td></tr>
    <tr><th>コメント数</th><td><%= @board.board_comments.count %></td></tr>
  </table>
  <table class="table table-hover col-8 offset-md-2">
    <% @board.board_comments.each do |bc| %>
      <tr class="moves-contents" onclick='window.location="/admin/board_comments/<%= bc.id %>"' role="link">
        <th><%= image_tag bc.user.get_image(30,30) %><%= bc.user.name %></th><td><%= bc.body %></td>
      </tr>
    <% end %>
  </table>
  <%= link_to "投稿を削除する",admin_board_path,method: :delete,class: "offset-md-6" %>
</div>