config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"

  namespace :admin do
    resources :posts, only: [:index, :show, :update, :destroy]
    resources :users, only: [:index, :show, :update]
    resources :comments, only: [:index, :show, :destroy]
    resources :boards, only: [:index, :show, :destroy]
    resources :board_comments, only: [:index, :show, :destroy]
    resources :searches, only: :index
    get"search" => "searches#search"
  end

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, controllers: {
    sessions: "public/sessions",
    registrations: "public/registrations"
  }

  scope module: :public do
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :edit, :update, :destroy]
    end
    resources :searches, only: :index
    get"search" => "searches#search"
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get"followings" => "relationships#followings", as: "followings"
      get"followers" => "relationships#followers", as: "followers"
      member do
        get :favorites
      end
    end
    resources :boards, only: [:new, :index, :show, :create] do
      resources :board_comments, only: [:create], shallow: true
    end
    resources :notifications, only: :index
    resources :mini_messages, only: :create
    resources :mini_rooms, only: [:create,:index,:show]
    get "user/confirm" => "users#confirm" #退会確認画面
    patch "user/withdrawal" => "users#withdrawal" #論理削除用のルーティング
    post "guest_sign_in" => "sessions#guest_sign_in" #ゲストログイン用のルーティング
  end

 devise_scope :user do
   post "users/guest_sign_in" => "public/sessions#guest_sign_in"
 end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_modal_sidemenu.html.erb
<div class="modal left fade" id="modal-s" tabindex="-1">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title text-light" id="ModalLabel"><%= link_to "Game Connect",root_path,class: "text-light"%></h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" class="text-light">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul class="navbar-nav flex-column ml-auto" style="height: 100vh">
          <% if user_signed_in? %>
            <li class="nav-item m-2">
              <%= link_to destroy_user_session_path,method: :delete,class: "nav-link text-light" do %>
                <h5><i class="fas fa-right-from-bracket"></i> ログアウト</h5>
              <% end %>
            </li>
            <li class="nav-item m-2">
              <%= link_to posts_path,class: "nav-link text-light" do %>
                <h5><i class="fas fa-gamepad"></i> 投稿一覧</h5>
              <% end %>
            </li>
            <% if current_user.email != "guest@example.com" %>
              <li class="nav-item m-2">
                <%= link_to new_post_path,class: "nav-link text-secondary" do %>
                <h5><i class="fas fa-pen"></i> 投稿する</h5><% end %>
              </li>
            <% end %>
            <li class="nav-item m-2">
              <%= link_to boards_path,class: "nav-link text-light" do %>
                <h5><i class="fas fa-chalkboard-user"></i> 掲示板</h5>
              <% end %>
            </li>
            <!--li class="nav-item m-2">
              <%#= link_to public_user_path(current_user),class: "nav-link text-light" do %>
                <h5><i class="fas fa-house"></i> マイページ</h5>
              <%# end %>
            </li-->
            <% if current_user.email != "guest@example.com" %>
              <li class="nav-item m-2">
                <%= link_to favorites_user_path(current_user),class: "nav-link text-secondary" do %>
                <h5><i class="fas fa-heart"></i> お気に入り</h5><% end %>
              </li>
            <% end %>
          <% elsif admin_signed_in? %>
            <li class="nav-item m-2">
              <%= link_to admin_users_path,class: "nav-link text-light" do %>
                <h5><i class="fas fa-users"></i> ユーザー一覧</h5>
              <% end %>
            </li>
            <li class="nav-item m-2">
              <%= link_to admin_posts_path,class: "nav-link text-light" do %>
                <h5><i class="fas fa-list"></i> 投稿一覧</h5>
              <% end %>
            </li>
            <li class="nav-item m-2">
              <%= link_to admin_comments_path,class: "nav-link text-light" do %>
                <h5><i class="fas fa-comments"></i> コメント一覧</h5>
              <% end %>
            </li>
            <li class="nav-item m-2">
              <%= link_to admin_boards_path,class: "nav-link text-light" do %>
                <h5><i class="fas fa-chalkboard"></i> 掲示板一覧</h5>
              <% end %>
            </li>
            <li class="nav-item m-2">
              <%= link_to admin_board_comments_path,class: "nav-link text-light" do %>
                <h5><i class="fas fa-chalkboard"></i> 掲示板コメント一覧</h5>
              <% end %>
            </li>
            <li class="nav-item m-2">
              <%= link_to destroy_admin_session_path,method: :delete,class: "nav-link text-light" do %>
                <h5><i class="fas fa-right-from-bracket"></i> 管理者ログアウト</h5>
              <% end %>
            </li>
          <% else %>
            <li class="nav-item m-2">
              <%= link_to new_user_session_path,class: "nav-link text-light" do %>
                <h5><i class="fas fa-right-to-bracket"></i> ログイン</h5>
              <% end %>
            </li>
            <li class="nav-item m-2">
            <%= link_to users_guest_sign_in_path, method: :post,class: "nav-link text-light text-nowrap" do %>
                <h5><i class="fas fa-user"></i> ゲストログイン(閲覧用)</h5>
              <% end %>
            </li>
            <li class="nav-item m-2">
              <%= link_to new_admin_session_path,class: "nav-link text-light" do %>
                <h5><i class="fas fa-user-tie"></i> 管理者ログイン</h5>
              <% end %>
            </li>
          <% end %>
        </ul>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/_pc_sidemenu.html.erb
<nav class = "bg-light m-2 p-2 sidemenu-fixed">
  <ul class="navbar-nav flex-column ml-auto" style="height: 100vh">
    <% if user_signed_in? %>
      <li class="nav-item m-2">
        <%= link_to destroy_user_session_path,method: :delete,class: "nav-link text-secondary" do %>
          <h5><i class="fas fa-right-from-bracket"></i> ログアウト</h5>
        <% end %>
      </li>
      <li class="nav-item m-2">
        <%= link_to posts_path,class: "nav-link text-secondary" do %>
          <h5><i class="fas fa-gamepad"></i> 投稿一覧</h5>
        <% end %>
      </li>
      <% if current_user.email != "guest@example.com" %>
        <li class="nav-item m-2">
          <%= link_to new_post_path,class: "nav-link text-secondary" do %>
          <h5><i class="fas fa-pen"></i> 投稿する</h5><% end %>
        </li>
      <% end %>
      <li class="nav-item m-2">
        <%= link_to boards_path,class: "nav-link text-secondary" do %>
          <h5><i class="fas fa-chalkboard-user"></i> 掲示板</h5>
        <% end %>
      </li>
      <!--li class="nav-item m-2">
        <%#= link_to public_user_path(current_user),class: "nav-link text-light" do %>
          <h5><i class="fas fa-house"></i> マイページ</h5>
        <%# end %>
      </li-->
      <% if current_user.email != "guest@example.com" %>
        <li class="nav-item m-2">
          <%= link_to favorites_user_path(current_user),class: "nav-link text-secondary" do %>
          <h5><i class="fas fa-heart"></i> お気に入り</h5><% end %>
        </li>
      <% end %>
    <% elsif admin_signed_in? %>
      <li class="nav-item m-2">
        <%= link_to admin_users_path,class: "nav-link text-secondary" do %>
          <h5><i class="fas fa-users"></i> ユーザー一覧</h5>
        <% end %>
      </li>
      <li class="nav-item m-2">
        <%= link_to admin_posts_path,class: "nav-link text-secondary" do %>
          <h5><i class="fas fa-list"></i> 投稿一覧</h5>
        <% end %>
      </li>
      <li class="nav-item m-2">
        <%= link_to admin_comments_path,class: "nav-link text-secondary" do %>
          <h5><i class="fas fa-comments"></i> コメント一覧</h5>
        <% end %>
      </li>
      <li class="nav-item m-2">
        <%= link_to admin_boards_path,class: "nav-link text-secondary" do %>
          <h5><i class="fas fa-chalkboard"></i> 掲示板一覧</h5>
        <% end %>
      </li>
      <li class="nav-item m-2">
        <%= link_to admin_board_comments_path,class: "nav-link text-secondary" do %>
          <h5><i class="fas fa-chalkboard"></i> 掲示板コメント一覧</h5>
        <% end %>
      </li>
      <li class="nav-item m-2">
        <%= link_to destroy_admin_session_path,method: :delete,class: "nav-link text-secondary" do %>
          <h5><i class="fas fa-right-from-bracket"></i> 管理者ログアウト</h5>
        <% end %>
      </li>
    <% else %>
      <li class="nav-item m-2">
        <%= link_to new_user_session_path,class: "nav-link text-secondary" do %>
          <h5><i class="fas fa-right-to-bracket"></i> ログイン</h5>
        <% end %>
      </li>
      <li class="nav-item m-2">
      <%= link_to users_guest_sign_in_path, method: :post,class: "nav-link text-secondary text-nowrap" do %>
          <h5><i class="fas fa-user"></i> ゲストログイン</h5>
        <% end %>
      </li>
      <li class="nav-item m-2">
        <%= link_to new_admin_session_path,class: "nav-link text-secondary" do %>
          <h5><i class="fas fa-user-tie"></i> 管理者ログイン</h5>
        <% end %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/_sidemenu.html.erb
<div class="modal left fade" id="modal-s" tabindex="-1">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title text-light" id="ModalLabel"><a href="/">Game Connect</a></h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" class="text-light">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul class="navbar-nav flex-column ml-auto" style="height: 100vh">
          <% if user_signed_in? %>
            <li class="nav-item m-2">
              <%= link_to destroy_user_session_path,method: :delete,class: "nav-link text-light" do %>
                <h5><i class="fas fa-right-from-bracket"></i> ログアウト</h5>
              <% end %>
            </li>
            <li class="nav-item m-2">
              <%= link_to public_posts_path,class: "nav-link text-light" do %>
                <h5><i class="fas fa-gamepad"></i> 投稿一覧</h5>
              <% end %>
            </li>
            <li class="nav-item m-2">
              <%= link_to new_public_post_path,class: "nav-link text-light" do %>
                <h5><i class="fas fa-pen"></i> 投稿する</h5>
              <% end %>
            </li>
            <li class="nav-item m-2">
              <%= link_to public_boards_path,class: "nav-link text-light" do %>
                <h5><i class="fas fa-chalkboard-user"></i> 掲示板</h5>
              <% end %>
            </li>
            <!--li class="nav-item m-2">
              <%#= link_to public_user_path(current_user),class: "nav-link text-light" do %>
                <h5><i class="fas fa-house"></i> マイページ</h5>
              <%# end %>
            </li-->
            <li class="nav-item m-2">
              <%= link_to favorites_public_user_path(current_user),class: "nav-link text-light" do %>
                <h5><i class="fas fa-heart"></i> お気に入り</h5>
              <% end %>
            </li>
          <% elsif admin_signed_in? %>
            <li class="nav-item m-2">
              <%= link_to admin_users_path,class: "nav-link text-light" do %>
                <h5><i class="fas fa-users"></i> ユーザー一覧</h5>
              <% end %>
            </li>
            <li class="nav-item m-2">
              <%= link_to admin_posts_path,class: "nav-link text-light" do %>
                <h5><i class="fas fa-list"></i> 投稿一覧</h5>
              <% end %>
            </li>
            <li class="nav-item m-2">
              <%= link_to admin_comments_path,class: "nav-link text-light" do %>
                <h5><i class="fas fa-comments"></i> コメント一覧</h5>
              <% end %>
            </li>
            <li class="nav-item m-2">
              <%= link_to admin_boards_path,class: "nav-link text-light" do %>
                <h5><i class="fas fa-chalkboard"></i> 掲示板一覧</h5>
              <% end %>
            </li>
            <li class="nav-item m-2">
              <%= link_to admin_board_comments_path,class: "nav-link text-light" do %>
                <h5><i class="fas fa-chalkboard"></i> 掲示板コメント一覧</h5>
              <% end %>
            </li>
            <li class="nav-item m-2">
              <%= link_to destroy_admin_session_path,method: :delete,class: "nav-link text-light" do %>
                <h5><i class="fas fa-right-from-bracket"></i> 管理者ログアウト</h5>
              <% end %>
            </li>
          <% else %>
            <li class="nav-item m-2">
              <%= link_to new_user_session_path,class: "nav-link text-light" do %>
                <h5><i class="fas fa-right-to-bracket"></i> ログイン</h5>
              <% end %>
            </li>
            <li class="nav-item m-2">
            <%= link_to users_guest_sign_in_path, method: :post,class: "nav-link text-light text-nowrap" do %>
                <h5><i class="fas fa-user"></i> ゲストログイン(閲覧用)</h5>
              <% end %>
            </li>
            <li class="nav-item m-2">
              <%= link_to new_admin_session_path,class: "nav-link text-light" do %>
                <h5><i class="fas fa-user-tie"></i> 管理者ログイン</h5>
              <% end %>
            </li>
          <% end %>
        </ul>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gameconnect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- drawer.css -->
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.1/css/drawer.min.css">-->
    <!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>-->
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/iScroll/5.1.3/iscroll.min.js"></script>-->
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.1.0/js/drawer.min.js"></script>-->

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/c44cf8e6f4.js" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  </head>

  <body class="h-100 w-100">
    <header role="banner">
      <div class="container-fluid bg-dark" style="height: 70px;">
        <div class="row">
          <div class="col-2 d-block d-lg-none">
            <button type="button" class="btn" data-toggle="modal" data-target="#modal-s">
              <i class="fas fa-bars fa-2x text-light p-2"></i>
            </button>
            <%= render 'layouts/modal_sidemenu' %>
          </div>
          <div class="col-3 d-none d-lg-block pt-2">
            <h3 class="modal-title"><%= link_to "Game Connect",root_path,class: "text-light p-3"%></h3>
          </div>
            <% if user_signed_in? %>
              <%= render 'public/shared/search'%>
              <% if current_user.email != "guest@example.com" %>
                <% if unchecked_notifications.any? %>
                  <%= link_to notifications_path,class: "nav-link text-secondary ml-auto" do %>
                    <span class="fa-stack"><i class="fas fa-bell fa-stack-2x"></i><i class="n-circle fas fa-circle fa-stack-1x" style="color:red;"></i></span>
                  <% end %>
                <% else %>
                  <%= link_to notifications_path,class: "nav-link text-secondary ml-auto" do %>
                    <i class="fas fa-bell fa-2x"></i>
                  <% end %>
                <% end %>
                <%#= link_to mini_rooms_path,class: "nav-link text-secondary" do %>
                  <!--<i class="fas fa-message fa-2x"></i>-->
                <%# end %>
              <% end %>
              <%= link_to user_path(current_user),class: "nav-link" do %>
              <%= image_tag current_user.get_image(40,40),class: "border border-secondary bg-light rounded-circle" %><% end %>
            <%# elsif admin_signed_in? %>
              <%#= render 'admin/shared/search' %>
            <% end %>
          </div>
        </div>
      </div>
    </header>

    <div class="container-fluid bg-light body-box">
        <main class="bg-light row">
          <div class="col-3 m-0 p-0 d-none d-lg-block border-right">
            <%= render 'layouts/pc_sidemenu' %>
          </div>
          <div class="col-12 col-lg-9 m-0 p-0 bg-light" style="height: 100vh">
            <div class="flash">
              <% if flash[:notice] %>
                <p class="text-success text-center"><%= notice %></p>
              <% elsif flash[:alert] %>
                <p class="text-danger text-center"><%= alert %></p>
              <% end %>
            </div>
            <%= yield %>
          </div>
        </main>
      </div>
  </body>
</html>

app/views/layouts/application.html_BACKUP_7850.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gameconnect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- drawer.css -->
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.1/css/drawer.min.css">-->
    <!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>-->
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/iScroll/5.1.3/iscroll.min.js"></script>-->
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.1.0/js/drawer.min.js"></script>-->

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/c44cf8e6f4.js" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  </head>

  <body class="h-100 w-100">
    <header role="banner">
      <div class="container-fluid bg-dark" style="height: 70px;">
        <div class="row">
          <div class="col-2 d-block d-lg-none">
            <button type="button" class="btn" data-toggle="modal" data-target="#modal-s">
              <i class="fas fa-bars fa-2x text-light p-2"></i>
            </button>
            <%= render 'layouts/modal_sidemenu' %>
          </div>
          <div class="col-3 d-none d-lg-block pt-2">
            <h3 class="modal-title"><%= link_to "Game Connect",root_path,class: "text-light p-3"%></h3>
          </div>
            <% if user_signed_in? %>
              <%= render 'public/shared/search'%>
              <% if current_user.email != "guest@example.com" %>
                <% if unchecked_notifications.any? %>
                  <%= link_to notifications_path,class: "nav-link text-secondary ml-auto" do %>
                    <span class="fa-stack"><i class="fas fa-bell fa-stack-2x"></i><i class="n-circle fas fa-circle fa-stack-1x" style="color:red;"></i></span>
                  <% end %>
                <% else %>
                  <%= link_to notifications_path,class: "nav-link text-secondary ml-auto" do %>
                    <i class="fas fa-bell fa-2x"></i>
                  <% end %>
<<<<<<< HEAD
=======
                <% end %>
                <%= link_to mini_rooms_path,class: "nav-link text-secondary" do %>
                  <i class="fas fa-message fa-2x"></i>
>>>>>>> origin/main
                <% end %>
                <%#= link_to mini_rooms_path,class: "nav-link text-secondary" do %>
                  <!--<i class="fas fa-message fa-2x"></i>-->
                <%# end %>
              <% end %>
              <%= link_to user_path(current_user),class: "nav-link" do %>
              <%= image_tag current_user.get_image(40,40),class: "border border-secondary bg-light rounded-circle" %><% end %>
            <%# elsif admin_signed_in? %>
              <%#= render 'admin/shared/search' %>
            <% end %>
          </div>
        </div>
      </div>
    </header>

    <div class="container-fluid bg-light body-box">
        <main class="bg-light row">
          <div class="col-3 m-0 p-0 d-none d-lg-block border-right">
            <%= render 'layouts/pc_sidemenu' %>
          </div>
          <div class="col-12 col-lg-9 m-0 p-0 bg-light" style="height: 100vh">
            <div class="flash">
              <% if flash[:notice] %>
                <p class="text-success text-center"><%= notice %></p>
              <% elsif flash[:alert] %>
                <p class="text-danger text-center"><%= alert %></p>
              <% end %>
            </div>
            <%= yield %>
          </div>
        </main>
      </div>
  </body>
</html>

app/views/layouts/application.html_LOCAL_7850.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gameconnect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- drawer.css -->
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.1/css/drawer.min.css">-->
    <!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>-->
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/iScroll/5.1.3/iscroll.min.js"></script>-->
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.1.0/js/drawer.min.js"></script>-->

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/c44cf8e6f4.js" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  </head>

  <body class="h-100 w-100">
    <header role="banner">
      <div class="container-fluid bg-dark" style="height: 70px;">
        <div class="row">
          <div class="col-2 d-block d-lg-none">
            <button type="button" class="btn" data-toggle="modal" data-target="#modal-s">
              <i class="fas fa-bars fa-2x text-light p-2"></i>
            </button>
            <%= render 'layouts/modal_sidemenu' %>
          </div>
          <div class="col-3 d-none d-lg-block pt-2">
            <h3 class="modal-title"><%= link_to "Game Connect",root_path,class: "text-light p-3"%></h3>
          </div>
            <% if user_signed_in? %>
              <%= render 'public/shared/search'%>
              <% if current_user.email != "guest@example.com" %>
                <% if unchecked_notifications.any? %>
                  <%= link_to notifications_path,class: "nav-link text-secondary ml-auto" do %>
                    <span class="fa-stack"><i class="fas fa-bell fa-stack-2x"></i><i class="n-circle fas fa-circle fa-stack-1x" style="color:red;"></i></span>
                  <% end %>
                <% else %>
                  <%= link_to notifications_path,class: "nav-link text-secondary ml-auto" do %>
                    <i class="fas fa-bell fa-2x"></i>
                  <% end %>
                <% end %>
                <%#= link_to mini_rooms_path,class: "nav-link text-secondary" do %>
                  <!--<i class="fas fa-message fa-2x"></i>-->
                <%# end %>
              <% end %>
              <%= link_to user_path(current_user),class: "nav-link" do %>
              <%= image_tag current_user.get_image(40,40),class: "border border-secondary bg-light rounded-circle" %><% end %>
            <%# elsif admin_signed_in? %>
              <%#= render 'admin/shared/search' %>
            <% end %>
          </div>
        </div>
      </div>
    </header>

    <div class="container-fluid bg-light body-box">
        <main class="bg-light row">
          <div class="col-3 m-0 p-0 d-none d-lg-block border-right">
            <%= render 'layouts/pc_sidemenu' %>
          </div>
          <div class="col-12 col-lg-9 m-0 p-0 bg-light" style="height: 100vh">
            <div class="flash">
              <% if flash[:notice] %>
                <p class="text-success text-center"><%= notice %></p>
              <% elsif flash[:alert] %>
                <p class="text-danger text-center"><%= alert %></p>
              <% end %>
            </div>
            <%= yield %>
          </div>
        </main>
      </div>
  </body>
</html>

app/views/layouts/search.html.erb
<h2>検索結果</h2>

<table class="table table-hover table-inverse">
  <!--検索対象モデルがUserの時-->
  <% if @range == "User" %>
    <tbody>
      <% @users.each do |u| %>
        <tr>
          <td><%= u.name %></td>
          <td><%= u.introduction %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <!--検索対象モデルがUserではない時(= 検索対象モデルがPostの時) -->
    <tbody>
      <% @posts.each do |po| %>
        <tr>
          <td><%= po.user.name %></td>
          <td><%= po.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>